import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import {spawn} from 'node:child_process';
import {browser,sleep} from './browser.mjs';

const root=path.resolve(import.meta.dirname,'..'),port=8878,base=`http://127.0.0.1:${port}`;
const data=path.join(root,'artifacts','cli-browser-test-'+Date.now());
await fs.mkdir(data,{recursive:true});
const server=spawn(path.join(root,'.venv','Scripts','python.exe'),[path.join(root,'scripts','cli_fixture.py')],{
  cwd:root,env:{...process.env,MEDIA_DATA_DIR:data,CLI_TEST_PORT:String(port)},windowsHide:true,stdio:['ignore','pipe','pipe']});
let log='';server.stdout.on('data',d=>{log+=d});server.stderr.on('data',d=>{log+=d});
let b;
const checks=[];
try {
  let ready=false;
  for(let i=0;i<150;i++){try{ready=(await fetch(base+'/api/environment')).ok;if(ready)break;}catch{}await sleep(100);}
  assert.ok(ready,log);
  b=await browser(root,9238);
  const {cdp,evaluate,waitFor,shot}=b;
  await cdp('Page.navigate',{url:base});await waitFor(`!!document.querySelector('#creation-idea')`);
  await evaluate(`document.querySelector('[data-page="settings"]').click()`);
  await waitFor(`!!document.querySelector('#cli-path')`);
  await evaluate(`document.querySelector('[data-action="v2-cli-check"]').click()`);
  await waitFor(`S.env.claude_cli.last_check?.logged_in===true`);
  assert.equal(await evaluate(`document.querySelectorAll('#connection-key').length`),0);
  await shot('cli-settings');checks.push('CLI check and settings without API key');
  await evaluate(`document.querySelector('[data-page="home"]').click()`);
  await waitFor(`!!document.querySelector('#creation-idea')`);
  await evaluate(`document.querySelector('#creation-idea').value='制作一个展示节奏变化的竖屏视频';document.querySelector('[data-action="v2-direct-video"]').click()`);
  await waitFor(`!!document.querySelector('#cli-prompt')`);
  await waitFor(`!!document.querySelector('#cut-player')`,20000);
  await waitFor(`document.querySelector('#cut-player').readyState>=1`);
  await evaluate(`document.querySelector('#cut-player').muted=true;Promise.race([document.querySelector('#cut-player').play(),new Promise((_,reject)=>setTimeout(()=>reject(new Error('Video playback timed out')),5000))])`);
  await waitFor(`document.querySelector('#cut-player').currentTime>.3&&document.querySelector('#cut-player').readyState>=2`);
  await evaluate(`document.querySelector('#cut-player').pause()`);
  assert.equal(await evaluate(`S.detail.tasks.some(t=>t.kind==='research')`),false);
  assert.equal(await evaluate(`S.detail.versions[0].result.engine`),'claude_cli');
  assert.equal(await evaluate(`S.detail.versions[0].preview.checks.decodable`),true);
  assert.equal(await evaluate(`S.detail.versions[0].preview.subtitles`),undefined);
  assert.ok(await evaluate(`document.querySelector('#cut-player').duration>0`));
  await shot('cli-video');checks.push('Prompt to validated playable MP4');
  const first=await evaluate(`S.detail.versions[0].id`);
  await evaluate(`document.querySelector('#cli-prompt').value='开头更有冲击力';document.querySelector('#cli-prompt').dispatchEvent(new Event('input',{bubbles:true}));document.querySelector('[data-action="v2-cli-run"]').click()`);
  await waitFor(`S.detail.versions.filter(v=>v.stage==='edit').length===2`,20000);
  assert.equal(await evaluate(`S.detail.versions[0].parent_id`),first);
  assert.notEqual(await evaluate(`S.detail.versions[0].cli_session_id`),await evaluate(`S.detail.versions[1].cli_session_id`));
  const video=await evaluate(`S.detail.versions[0].final.video`);
  const project=await evaluate(`S.selected`);
  assert.equal((await fetch(`${base}/api/projects/${project}/files/${video}`)).status,200);
  checks.push('Follow-up creates a separate session and downloadable video');
  await evaluate(`document.querySelector('[data-action="v2-advanced-edit"]').click()`);
  await waitFor(`!!document.querySelector('#preview-player')`);
  assert.equal(await evaluate(`!!document.querySelector('#cli-prompt')`),true);
  checks.push('Advanced view supports CLI video and editing prompt');
  await cdp('Page.navigate',{url:base+`/#workspace/${project}/video`});
  await waitFor(`!!document.querySelector('#cut-player')`);
  assert.equal(await evaluate(`document.querySelector('#cli-prompt').value`),'开头更有冲击力');
  checks.push('Reload preserves project, video, and prompt');
  await cdp('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});
  await shot('cli-video-mobile');
  assert.equal(await evaluate(`document.documentElement.scrollWidth<=innerWidth+1`),true);
  await evaluate(`document.querySelector('[data-page="settings"]').click()`);
  await waitFor(`!!document.querySelector('#cli-path')`);
  await shot('cli-settings-mobile');
  assert.equal(await evaluate(`document.documentElement.scrollWidth<=innerWidth+1`),true);
  checks.push('Mobile video and settings fit viewport');
  assert.deepEqual(b.errors,[]);
  const result={status:'PASS',checks,browserErrors:b.errors,dataDirectory:data,cli:'fixture subprocess',media:'real FFmpeg MP4'};
  await fs.writeFile(path.join(root,'artifacts','cli-browser-results.json'),JSON.stringify(result,null,2));
  console.log(JSON.stringify(result));
}finally{b?.close();server.kill();}
